set wildmenu
set hidden

filetype off 

set formatoptions+=1r
syntax on
set lbr
set number

set nowrap
set linebreak
set sidescroll=5
set listchars+=precedes:<
set listchars+=extends:>

set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set backspace=2

set incsearch
set ignorecase
set smartcase
set hlsearch

hi TabLineFill ctermfg=7 ctermbg=7
hi TabLine cterm=bold ctermfg=7
hi TabLineSel cterm=bold
set showtabline=2

nnoremap gg ggz.
